name: CI/CD for Backend - Spring Boot
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up backend environment variables
        env:
          DB_URL: ${{ secrets.DB_URL }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
         echo "spring.datasource.url=${DB_URL}" >> backend/src/main/resources/application.properties
         echo "spring.datasource.username=${DB_USERNAME}" >> backend/src/main/resources/application.properties
         echo "spring.datasource.password=${DB_PASSWORD}" >> backend/src/main/resources/application.properties
         
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build with Maven
        run: |
          cd backend
          mvn clean install -Dmaven.test.skip=true
          
      - name: Copy JAR file to EC2
        uses: appleboy/scp-action@master
        with:
         host: 52.90.64.223
         username: ec2-user
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: 22
         source: backend/target/student-0.0.1-SNAPSHOT.jar
         target: /home/ec2-user/
         
      - name: Copy JAR file to EC2
        uses: appleboy/scp-action@master
        with:
         host: 54.152.139.115
         username: ec2-user
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: 22
         source: backend/target/student-0.0.1-SNAPSHOT.jar
         target: /home/ec2-user/
    
      - name: Copy JAR file to EC2
        uses: appleboy/scp-action@master
        with:
          host: 100.26.133.66
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: backend/target/student-0.0.1-SNAPSHOT.jar
          target: /home/ec2-user/

      - name: Connect to EC2 and run command
        uses: appleboy/ssh-action@master
        with:
            host: 52.90.64.223, 54.152.139.115, 100.26.133.66
            username: ec2-user
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
             sudo java -jar backend/target/student-0.0.1-SNAPSHOT.jar -Dspring.profiles.active=production

         
     
             














