name: CI/CD for Backend - Spring Boot
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build with Maven
        run: |
          cd backend
          mvn clean install -Dmaven.test.skip=true
          
      - name: Configure SSH key
        run: |
         mkdir -p ~/.ssh
         echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         ssh-keyscan 54.204.107.31 >> ~/.ssh/known_hosts 

      - name: Copy JAR file to EC2
        uses: appleboy/scp-action@master
        with:
         host: 54.204.107.31
         username: ec2-user
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: 22
         source: backend/target/student-0.0.1-SNAPSHOT.jar
         target: /home/ec2-user/
         
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
         node-version: '18'

      - name: Install dependencies
        run: |
         cd frontend
         npm install

      - name: Build the application
        run: |
         cd frontend
         npm run build
         
      - name: Copy  to EC2 instance
        uses: appleboy/scp-action@master
        with:
         host: 54.204.107.31
         username: ec2-user
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: 22
         source: frontend/build/
         target: /home/ec2-user/
         
      - name: Connect to EC2 and run command
        uses: appleboy/ssh-action@master
        with:
            host: 54.204.107.31
            username: ec2-user
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
             sudo mv backend /root/
             sudo su -
             cd backend
             cd target
             sudo  java -jar student-0.0.1-SNAPSHOT.jar














