name: CI/CD for Backend - Spring Boot
on:
  push:
    branches:
      - main # Ovdje specificiraj granu koju želiš pratiti (može biti i neka druga grana)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17' # Ovdje specificiraj verziju JDK koju koristiš (potrebna verzija za Spring Boot 2.5+)

      - name: Build with Maven
        run: mvn package

