name: CI/CD for Backend - Spring Boot
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build with Maven
        run: |
          cd backend
          mvn clean install -Dmaven.test.skip=true
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: backend/target/web-app.jar
          
      - name: Set up SSH key
        run: echo "${EC2_PRIVATE_KEY}" > vedad-varupa-web-server-key.pem
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
      - name: Set permissions for SSH key
        run: chmod 600 vedad-varupa-web-server-key.pem 
        
      - name: Copy SSH key to EC2 instance
        run: scp -i vedad-varupa-web-server-key.pem vedad-varupa-web-server-key.pem ${EC2_USERNAME}@${EC2_HOST}:~/
        
      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
          
            scp -i vedad-varupa-web-server-key.pem  $GITHUB_WORKSPACE/backend/target/web-app.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/ec2-user/

            ssh -i vedad-varupa-web-server-key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /home/ec2-user/ && java -jar web-app.jar"









