name: CI/CD for Backend - Spring Boot
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build with Maven
        run: |
          cd backend
          mvn clean install -Dmaven.test.skip=true
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: web-app
          path: backend/target/web-app.jar 
    
      - name: SSH into EC2 instance and deploy
        run: |
          ssh -i ${{ secrets.EC2_PRIVATE_KEY }}  ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "cd /home/ec2-user/ && java -jar web-app.jar"














