name: CI/CD for Backend - Spring Boot
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Build with Maven
        run: |
          cd backend
          mvn clean install -Dmaven.test.skip=true
          
      - name: Configure SSH key
        run: |
         mkdir -p ~/.ssh
         echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
         chmod 600 ~/.ssh/id_rsa
         ssh-keyscan 54.204.107.31 >> ~/.ssh/known_hosts

      - name: Connect to EC2 and run command
        uses: appleboy/ssh-action@master
        with:
            host: 54.204.107.31
            username: ec2-user
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
             echo "Hello from GitHub Actions! I'm running on the EC2 instance."














