name: CI/CD for Frontend - React
on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
            
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
         node-version: '18'

      - name: Install dependencies
        run: |
         cd frontend
         npm install

      - name: Build the application
        run: |
         cd frontend
         npm run build
         
      - name: Copy  to EC2 instance
        uses: appleboy/scp-action@master
        with:
         host: 52.90.64.223
         username: ec2-user
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: 22
         source: frontend/.
         target: /home/ec2-user/

      - name: Copy  to EC2 instance
        uses: appleboy/scp-action@master
        with:
         host: 54.152.139.115
         username: ec2-user
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: 22
         source: frontend/.
         target: /home/ec2-user/
         
      - name: Copy  to EC2 instance
        uses: appleboy/scp-action@master
        with:
         host: 100.26.133.66
         username: ec2-user
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: 22
         source: frontend/.
         target: /home/ec2-user/

      - name: Connect to EC2 and run 
        uses: appleboy/ssh-action@master
        with:
            host: 52.90.64.223, 54.152.139.115, 100.26.133.66
            username: ec2-user
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: 22
            script: |
              cd frontend
              npm install
              npm start

     


             
     
